# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: 'latest'
    
    - name: Restore NuGet packages
      run: nuget restore YourSolution.sln
    
    - name: Build solution
      run: msbuild YourSolution.sln /p:Configuration=Release /p:Platform="Any CPU"
    
    - name: Run tests (if you have MSTest/NUnit)
      run: |
        # For MSTest
        vstest.console.exe **\bin\Release\*Test*.dll
        # Or for NUnit (uncomment if using NUnit)
        # nunit3-console.exe **\bin\Release\*Test*.dll

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          **/bin/Release/
          !**/bin/Release/**/*.pdb
          !**/bin/Release/**/obj/
